# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='ifallow',
            field=models.TextField(default='NO'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='numb',
            field=models.TextField(default=''),
        ),
    ]
