# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20160501_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='ifallow',
            field=models.TextField(default='yes'),
        ),
    ]
